baseURL = "https://fluxcd.netlify.com"
title = "Flux"
enableRobotsTXT = true

# Disable taxonomies globally
disableKinds = ["taxonomy", "taxonomyTerm"]

# Language configuration
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

# Markup settings
# Ref: https://gohugo.io/getting-started/configuration-markup#goldmark
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "monokai"

# Provide .LastMod values
enableGitInfo = true

[languages]
[languages.en]
languageName = "English"
languageCode = "en-us"
time_format_default = "01/02/2006"
time_format_blog = "01/02/2006"

[[menus.main]]
identifier = "project"
name = "Project"

[[menus.main]]
name = "Code of conduct"
parent = "project"
url = "https://github.com/fluxcd/flux/blob/master/CODE_OF_CONDUCT.md"
weight = 1

[[menus.main]]
name = "Contributing"
parent = "project"
url = "https://github.com/fluxcd/flux/blob/master/CONTRIBUTING.md"
weight = 2

[[menus.main]]
name = "Branding"
parent = "project"
url = "https://branding.cncf.io/projects/flux"
weight = 3

[params]
description          = "Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit."
copyright            = "The Flux contributors"
github_repo          = "fluxcd/flux"
github_website_repo  = "fluxcd/fluxcd.io"
slack                = "https://cloud-native.slack.com/messages/flux"
mailing_list         = "https://lists.cncf.io/g/cncf-flux-dev"
font_awesome_version = "5.9.0"

[params.logos]
navbar = "flux-horizontal-white.png"
hero   = "flux-horizontal-color.png"
footer = "flux-stacked-white.png"
cncf   = "cncf-color.png"

[[params.fonts]]
name  = "Montserrat"
sizes = [300,400,600,700]
type  = "sans_serif"

# Flux hero element
[params.flux]
# title    = "Alternative title"
# subtitle = "The GitOps operator for Kubernetes"

[[params.flux.buttons]]
text  = "Get started"
color = "warning"
url   = "#"

[[params.flux.buttons]]
text = "Learn more"
url  = "#"

# Overview hero element
[params.overview]
title   = "Overview"
summary = """
Flux is a tool for keeping [Kubernetes](https://kubernetes.io) clusters in sync with sources of configuration (like Git repositories), and automating updates to configuration when there is new code to deploy.
"""

## Overview features
[[params.overview.features]]
icon   = "fab fa-git-square fa-3x"
header = "Declarative"
text   = """
Describe the entire desired state of your system in [Git](https://git-scm.com). This includes apps, configuration, dashboards, monitoring, and everything else.
"""

[[params.overview.features]]
icon   = "fas fa-robot fa-3x"
header = "Automated"
text   = """
Use [YAML](https://yaml.org) to enforce conformance to the declared system. You don't need to run [`kubectl`](https://kubectl.docs.kubernetes.io/) because all changes go through Git. Use diffing tools to detect divergence between observed and desired state and receive notifications.
"""

[[params.overview.features]]
icon   = "fas fa-code fa-3x"
header = "Code, not containers"
text   = """
With Flux, everything is controlled through pull requests, which means no learning curve for new developers. Just use your standard PR process. Your Git history provides a sequence of transactions, allowing you to recover system state from any snapshot. Fix a production issue via pull request rather than making changes to the running system.
"""

# Resources hero element
[params.resources]
title   = "Resources"
summary = """
If you are new to Flux, you might want to check out some of the following resources to get started.
"""

## Resource items
[[params.resources.items]]
title       = "Rawkode Live: Introduction to GitOps Toolkit with Stefan Prodan"
description = """
Check out Stefan's introduction to Flux at Rawkode Live.
"""
url         = "https://www.youtube.com/watch?v=HqTzuOBP0eY"

[[params.resources.items]]
title       = "The Power of GitOps with Flux v2 & GitOps Toolkit with Leigh Capili"
description = """
Leigh shows off the Power of GitOps with Flux. This is part 1 - stay tuned for the next installment.
"""
url         = "https://www.youtube.com/watch?v=0v5bjysXTL8"

[[params.resources.items]]
title       = " Introduction To GitOps and GitOps Toolkit by Stefan Prodan"
description = """
Alexis Richardson, CEO at Weaveworks and Stefan Prodan, maintainer of the Flux project introduce you to GitOps Toolkit.

Talk from Cloud Native Nordics Tech Talks.
"""
url         = "https://www.youtube.com/watch?v=qQBtSkgl7tI"


# Toolkit hero element
[params.toolkit]
title = "GitOps Toolkit"
subtitle = """
The GitOps Toolkit is the set of APIs and controllers that make up the
runtime for Flux v2. The APIs comprise Kubernetes custom resources,
which can be created and updated by a cluster user, or by other
automation tooling.
"""
image = "building-blocks.svg"

[[params.toolkit.buttons]]
text = "Get started"
color = "dark"
url = "https://toolkit.fluxcd.io/dev-guides/source-watcher/"

[[params.toolkit.buttons]]
text = "Learn more"
url = "https://toolkit.fluxcd.io/components/"

# Community hero element
[params.community]
title = "Community"
summary = """
The Flux project aspires to be the vendor-neutral home for GitOps in a Cloud Native world.

What we achieved up until today is only possible because of our community.
"""

[[params.community.highlights]]
title = "GitHub Discussions"
icon = "fab fa-github"
text  = """
Join the conversation in GitHub Discussions. Everything Flux v2 related ranging from specificiations and feature planning to Show & Tell happens here.

[Join the discussion today](https://github.com/fluxcd/toolkit/discussions)!
"""

[[params.community.highlights]]
title = "Slack"
titleBgColor = "slack-green"
icon = "fab fa-slack"
text  = """
If you want to talk to the Flux team and community in real-time, join us on Slack. This is a great way to get to know everyone.

[Get an invite](https://slack.cnfc.io), or [go to the `#flux` channel](https://cloud-native.slack.com/messages/flux)
"""

[[params.community.highlights]]
title = "Mailing list"
titleBgColor = "info"
icon = "far fa-paper-plane"
text  = """
Join our (low-traffic) mailing list to stay up to day on announcements and sporadic discussions.

[Join the mailing list](https://lists.cncf.io/g/cncf-flux-dev)!
"""
