name: Re-run build from 'main' on Netlify every six hours
on:
  schedule:
    - cron: '0 */6 * * *'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 'main' on Netlify
        run: |
          curl -X POST -d {} '${{ secrets.NETLIFY_BUILD_HOOK }}'
